services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: event-attendance-app-dev
    container_name: event-attendance-app-dev
    tty: true
    stdin_open: true
    user: java
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: $PWD
        target: /workspace/event-attendance-app
    working_dir: /workspace

  db:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/postgresql/data

volumes:
  db_volume:
    name: event-attendance-app_devcontainer_db
    driver: local
